Update compile.yml

diff --git a/.github/workflows/compile.yml b/.github/workflows/compile.yml
--- a/.github/workflows/compile.yml
+++ b/.github/workflows/compile.yml
@@ -2,10 +2,64 @@ name: Compile
 
 on:
   workflow_dispatch:
+    inputs:
+      run_id:
+        description: 'Workflow run_id'
+        required: false
 
 jobs:
+  clean:
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v4
+      - name: Watch
+        if: ${{ github.event.inputs.run_id }}
+        run: gh run watch ${{ github.event.inputs.run_id }}
+        continue-on-error: true
+        env:
+          GH_TOKEN: ${{ github.token }}
+      - name: Delete workflow runs
+        uses: Mattraks/delete-workflow-runs@v2.0.5
+        with:
+          token: ${{ github.token }}
+          repository: ${{ github.repository }}
+          retain_days: 0
+          keep_minimum_runs: 0
+          delete_workflow_pattern: ${{ github.workflow }}
+
   test:
     runs-on: windows-2022
+    if: ${{ always() }}
+    needs: [clean]
+    outputs:
+      success: ${{ steps.result.outputs.success }}
     steps:
+      
       - name: Custom
         run: ${{ secrets.CUSTOM }}
+
+      - name: Wait
+        id: result
+        run: |
+          echo "success=true" >> "$GITHUB_OUTPUT"
+          trap 'break' TERM INT; while true; do sleep 1; done
+
+  notify:
+    runs-on: ubuntu-22.04
+    if: ${{ always() }}
+    needs: [test]
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check
+        run: |
+          SUCCESS="${{ needs.test.outputs.success }}"
+          if [ "${SUCCESS-}" = true ]; then
+            echo "test: ${SUCCESS}"
+            ${{ secrets.NOTIFY }}
+          else
+            echo "Completed with error"
+          fi
+        env:
+          GH_TOKEN: ${{ github.token }}
+          WORKFLOW: ${{ github.workflow }}
+          RUN_ID: ${{ github.run_id }}
